repos:

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black-jupyter
        name: format jupyter notebooks with black
        args:
        - --line-length
        - "100"

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=500']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
    -   id: ruff
        files: '^.*\.py$'
        args:
        - "--config"
        - "pyproject.toml"
        - "--fix"
        - "--exit-non-zero-on-fix"
